name: billsplit_flutter
description: A new expense sharing experience
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+71

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  firebase_crashlytics: ^4.2.0

  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  path: ^1.8.2
  storage_inspector: ^0.4.0
  rxdart: ^0.28.0
  collection:
  get_it: ^7.2.0
  intl: ^0.19.0
  email_validator:
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  cupertino_will_pop_scope: ^1.2.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.3
  eraser: ^3.0.0
  camera: ^0.11.0+2
  flutter_animate: ^4.5.2
  package_info_plus: ^8.1.1
  uuid: ^4.5.1
  json_pretty: ^1.0.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  phone_number: ^2.1.0
  country_code_picker: ^3.1.0
  image_cropper: ^8.0.2
  google_mlkit_text_recognition: ^0.14.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.22.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splitsby_logo.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: normal
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
